# Generated by Django 5.2.17 on 2026-09-10 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecko_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'indexes': [models.Index(fields=['is_active'], name='core_coin_is_acti_0d030c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoinCurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('atl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_data', to='core.coin')),
            ],
            options={
                'verbose_name': 'Coin Current Data',
                'verbose_name_plural': 'Coins Current Data',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('atl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='core.coin')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['coin', '-timestamp'], name='core_priceh_coin_id_b6ef2f_idx')],
            },
        ),
    ]
