# Generated by Django 5.2.17 on 2026-08-31 13:28
# Schema changes already applied in 0012.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coincurrentdata_options_coin_image_url_and_more'),
    ]

    operations = []
