# Generated by Django 5.2.17 on 2026-08-31 13:31
# Schema changes already applied in 0012.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coincurrentdata_circulating_supply_and_more'),
    ]

    operations = []
