# Generated by Django 5.2.17 on 2026-08-31 15:00
# Schema changes already applied in 0012.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pricehistory_circulating_supply'),
    ]

    operations = []
