# Generated by Django 5.2.17 on 2026-08-31 16:53
# Schema changes already applied in 0012.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pricehistory_coin'),
    ]

    operations = []
